apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: ftp-data
    port: 20
    protocol: TCP
  - name: ftp-control
    port: 21
    protocol: TCP
  - name: first-port
    port: 30000
    protocol: TCP
  - name: second-port
    port: 30001
    protocol: TCP
  - name: third-port
    port: 30002
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      serviceAccount: services
      containers:
      - name: ftps
        image: container-ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 20
          name: ftp-data
        - containerPort: 21
          name: ftp-control
        - containerPort: 30000
          name: first-port
        - containerPort: 30001
          name: second-port
        - containerPort: 30002
          name: third-port
