apiVersion: v1
kind: ServiceAccount
metadata:
    name: services
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-service
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["services", "deployments", "daemonsets", "nodes", "statefulsets", "persistentvolumes", "persistentvolumeclaims", "pods", "ingress", "endpoints"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-service
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read-service
subjects:
- kind: ServiceAccount
  name: services
  namespace: default